name: Build
on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:
  test:
    strategy:
      matrix:
        os:
          - macos
          - ubuntu

    name: build
    runs-on: ${{ matrix.os }}-latest
    steps:
      - uses: actions/checkout@v4.2.0

      - uses: actions/setup-go@v5.0.2
        id: go
        with:
          go-version: "1.22"

      - name: build
        run: go build
