name: Build
on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:
  test:
    strategy:
      matrix:
        go_version:
          - "1.21"
          - "1.22"
        os:
          - macos
          - ubuntu
          - windows
        arch:
          - 386
          - amd64
        exclude:
          - os: macos
            arch: 386

    name: build
    runs-on: ${{ matrix.os }}-latest
    steps:
      - uses: actions/checkout@v4.1.6

      - uses: actions/setup-go@v5.0.1
        id: go
        with:
          go-version: ${{ matrix.go_version }}

      - name: build
        run: go build
